# 3.2 Exercise: Preparing for Exploratory Data Analysis - Rahul Rajeev

Examples and Exercises from Think Stats, 2nd Edition

http://thinkstats2.com

Copyright 2016 Allen B. Downey

MIT License: https://opensource.org/licenses/MIT


In [1]:
from os.path import basename, exists


def download(url):
    filename = basename(url)
    if not exists(filename):
        from urllib.request import urlretrieve

        local, _ = urlretrieve(url, filename)
        print("Downloaded " + local)


download("https://github.com/AllenDowney/ThinkStats2/raw/master/code/thinkstats2.py")
download("https://github.com/AllenDowney/ThinkStats2/raw/master/code/thinkplot.py")

In [2]:
download("https://github.com/AllenDowney/ThinkStats2/raw/master/code/nsfg.py")

download("https://github.com/AllenDowney/ThinkStats2/raw/master/code/2002FemPreg.dct")
download(
    "https://github.com/AllenDowney/ThinkStats2/raw/master/code/2002FemPreg.dat.gz"
)

## 1.1 Filling out the ch01ex.ipynb file

Read NSFG data into a Pandas DataFrame.

In [3]:
import nsfg

In [4]:
preg = nsfg.ReadFemPreg()
preg.head()

caseid  pregordr  howpreg_n  howpreg_p  moscurrp  nowprgdk  pregend1  \
0       1         1        NaN        NaN       NaN       NaN       6.0   
1       1         2        NaN        NaN       NaN       NaN       6.0   
2       2         1        NaN        NaN       NaN       NaN       5.0   
3       2         2        NaN        NaN       NaN       NaN       6.0   
4       2         3        NaN        NaN       NaN       NaN       6.0   

   pregend2  nbrnaliv  multbrth  ...  laborfor_i  religion_i  metro_i  \
0       NaN       1.0       NaN  ...           0           0        0   
1       NaN       1.0       NaN  ...           0           0        0   
2       NaN       3.0       5.0  ...           0           0        0   
3       NaN       1.0       NaN  ...           0           0        0   
4       NaN       1.0       NaN  ...           0           0        0   

       basewgt  adj_mod_basewgt      finalwgt  secu_p  sest  cmintvw  \
0  3410.389399      3869.349602   6448.271112       2     9      NaN   
1  3410.389399      3869.349602   6448.271112       2     9      NaN   
2  7226.301740      8567.549110  12999.542264       2    12      NaN   
3  7226.301740      8567.549110  12999.542264       2    12      NaN   
4  7226.301740      8567.549110  12999.542264       2    12      NaN   

   totalwgt_lb  
0       8.8125  
1       7.8750  
2       9.1250  
3       7.0000  
4       6.1875  

[5 rows x 244 columns]

Print the column names.

In [5]:
preg.columns

Index(['caseid', 'pregordr', 'howpreg_n', 'howpreg_p', 'moscurrp', 'nowprgdk',
       'pregend1', 'pregend2', 'nbrnaliv', 'multbrth',
       ...
       'laborfor_i', 'religion_i', 'metro_i', 'basewgt', 'adj_mod_basewgt',
       'finalwgt', 'secu_p', 'sest', 'cmintvw', 'totalwgt_lb'],
      dtype='object', length=244)

Select a single column name.

In [6]:
preg.columns[1]

'pregordr'

Select a column and check what type it is.

In [7]:
pregordr = preg['pregordr']
type(pregordr)

pandas.core.series.Series

Print a column.

In [8]:
pregordr

0        1
1        2
2        1
3        2
4        3
        ..
13588    1
13589    2
13590    3
13591    4
13592    5
Name: pregordr, Length: 13593, dtype: int64

Select a single element from a column.

In [9]:
pregordr[0]

1

Select a slice from a column.

In [10]:
pregordr[2:5]

2    1
3    2
4    3
Name: pregordr, dtype: int64

Select a column using dot notation.

In [11]:
pregordr = preg.pregordr

Count the number of times each value occurs.

In [12]:
preg.outcome.value_counts().sort_index()

1    9148
2    1862
3     120
4    1921
5     190
6     352
Name: outcome, dtype: int64

Check the values of another variable.

In [13]:
preg.birthwgt_lb.value_counts().sort_index()

0.0        8
1.0       40
2.0       53
3.0       98
4.0      229
5.0      697
6.0     2223
7.0     3049
8.0     1889
9.0      623
10.0     132
11.0      26
12.0      10
13.0       3
14.0       3
15.0       1
Name: birthwgt_lb, dtype: int64

Make a dictionary that maps from each respondent's `caseid` to a list of indices into the pregnancy `DataFrame`.  Use it to select the pregnancy outcomes for a single respondent.

In [14]:
caseid = 10229
preg_map = nsfg.MakePregMap(preg)
indices = preg_map[caseid]
preg.outcome[indices].values

array([4, 4, 4, 4, 4, 4, 1], dtype=int64)

Select the `birthord` column, print the value counts, and compare to results published in the [codebook](ftp://ftp.cdc.gov/pub/Health_Statistics/NCHS/Dataset_Documentation/NSFG/Cycle6Codebook-Pregnancy.pdf)

In [17]:
birthord = preg.birthord
birthord.value_counts().sort_index()

1.0     4413
2.0     2874
3.0     1234
4.0      421
5.0      126
6.0       50
7.0       20
8.0        7
9.0        2
10.0       1
Name: birthord, dtype: int64

We can also use `isnull` to count the number of nans.

In [18]:
preg.birthord.isnull().sum()

4445

Select the `prglngth` column, print the value counts, and compare to results published in the [codebook](ftp://ftp.cdc.gov/pub/Health_Statistics/NCHS/Dataset_Documentation/NSFG/Cycle6Codebook-Pregnancy.pdf)

In [19]:
preg.prglngth.value_counts().sort_index()

0       15
1        9
2       78
3      151
4      412
5      181
6      543
7      175
8      409
9      594
10     137
11     202
12     170
13     446
14      29
15      39
16      44
17     253
18      17
19      34
20      18
21      37
22     147
23      12
24      31
25      15
26     117
27       8
28      38
29      23
30     198
31      29
32     122
33      50
34      60
35     357
36     329
37     457
38     609
39    4744
40    1120
41     591
42     328
43     148
44      46
45      10
46       1
47       1
48       7
50       2
Name: prglngth, dtype: int64

To compute the mean of a column, you can invoke the `mean` method on a Series.  For example, here is the mean birthweight in pounds:

In [20]:
preg.totalwgt_lb.mean()

7.265628457623368

Create a new column named <tt>totalwgt_kg</tt> that contains birth weight in kilograms.  Compute its mean.  Remember that when you create a new column, you have to use dictionary syntax, not dot notation.

In [21]:
preg['totalwgt_kg'] = preg.totalwgt_lb / 2.2
preg.totalwgt_kg.mean()

3.302558389828807

`nsfg.py` also provides `ReadFemResp`, which reads the female respondents file and returns a `DataFrame`:

In [22]:
download("https://github.com/AllenDowney/ThinkStats2/raw/master/code/2002FemResp.dct")
download("https://github.com/AllenDowney/ThinkStats2/raw/master/code/2002FemResp.dat.gz")

In [23]:
resp = nsfg.ReadFemResp()

`DataFrame` provides a method `head` that displays the first five rows:

In [24]:
resp.head()

caseid  rscrinf  rdormres  rostscrn  rscreenhisp  rscreenrace  age_a  \
0    2298        1         5         5            1          5.0     27   
1    5012        1         5         1            5          5.0     42   
2   11586        1         5         1            5          5.0     43   
3    6794        5         5         4            1          5.0     15   
4     616        1         5         4            1          5.0     20   

   age_r  cmbirth  agescrn  ...  pubassis_i      basewgt  adj_mod_basewgt  \
0     27      902       27  ...           0  3247.916977      5123.759559   
1     42      718       42  ...           0  2335.279149      2846.799490   
2     43      708       43  ...           0  2335.279149      2846.799490   
3     15     1042       15  ...           0  3783.152221      5071.464231   
4     20      991       20  ...           0  5341.329968      6437.335772   

      finalwgt  secu_r  sest  cmintvw  cmlstyr  screentime   intvlngth  
0  5556.717241       2    18     1234     1222    18:26:36  110.492667  
1  4744.191350       2    18     1233     1221    16:30:59   64.294000  
2  4744.191350       2    18     1234     1222    18:19:09   75.149167  
3  5923.977368       2    18     1234     1222    15:54:43   28.642833  
4  7229.128072       2    18     1233     1221    14:19:44   69.502667  

[5 rows x 3087 columns]

Select the `age_r` column from `resp` and print the value counts.  How old are the youngest and oldest respondents?

In [26]:
resp.age_r.value_counts().sort_index()

#the youngest respondest is 15, the oldest respondent is 44

15    217
16    223
17    234
18    235
19    241
20    258
21    267
22    287
23    282
24    269
25    267
26    260
27    255
28    252
29    262
30    292
31    278
32    273
33    257
34    255
35    262
36    266
37    271
38    256
39    215
40    256
41    250
42    215
43    253
44    235
Name: age_r, dtype: int64

We can use the `caseid` to match up rows from `resp` and `preg`.  For example, we can select the row from `resp` for `caseid` 2298 like this:

In [27]:
resp[resp.caseid==2298]

caseid  rscrinf  rdormres  rostscrn  rscreenhisp  rscreenrace  age_a  \
0    2298        1         5         5            1          5.0     27   

   age_r  cmbirth  agescrn  ...  pubassis_i      basewgt  adj_mod_basewgt  \
0     27      902       27  ...           0  3247.916977      5123.759559   

      finalwgt  secu_r  sest  cmintvw  cmlstyr  screentime   intvlngth  
0  5556.717241       2    18     1234     1222    18:26:36  110.492667  

[1 rows x 3087 columns]

And we can get the corresponding rows from `preg` like this:

In [28]:
preg[preg.caseid==2298]

caseid  pregordr  howpreg_n  howpreg_p  moscurrp  nowprgdk  pregend1  \
2610    2298         1        NaN        NaN       NaN       NaN       6.0   
2611    2298         2        NaN        NaN       NaN       NaN       6.0   
2612    2298         3        NaN        NaN       NaN       NaN       6.0   
2613    2298         4        NaN        NaN       NaN       NaN       6.0   

      pregend2  nbrnaliv  multbrth  ...  religion_i  metro_i      basewgt  \
2610       NaN       1.0       NaN  ...           0        0  3247.916977   
2611       NaN       1.0       NaN  ...           0        0  3247.916977   
2612       NaN       1.0       NaN  ...           0        0  3247.916977   
2613       NaN       1.0       NaN  ...           0        0  3247.916977   

      adj_mod_basewgt     finalwgt  secu_p  sest  cmintvw  totalwgt_lb  \
2610      5123.759559  5556.717241       2    18      NaN       6.8750   
2611      5123.759559  5556.717241       2    18      NaN       5.5000   
2612      5123.759559  5556.717241       2    18      NaN       4.1875   
2613      5123.759559  5556.717241       2    18      NaN       6.8750   

      totalwgt_kg  
2610     3.125000  
2611     2.500000  
2612     1.903409  
2613     3.125000  

[4 rows x 245 columns]

How old is the respondent with `caseid` 1?

In [31]:
resp[resp.caseid==1].age_r

1069    44
Name: age_r, dtype: int64

What are the pregnancy lengths for the respondent with `caseid` 2298?

In [34]:
preg[preg.caseid==2298].prglngth

2610    40
2611    36
2612    30
2613    40
Name: prglngth, dtype: int64

What was the birthweight of the first baby born to the respondent with `caseid` 5012?

In [35]:
preg[preg.caseid==5012].birthwgt_lb

5515    6.0
Name: birthwgt_lb, dtype: float64

## 1.2 Reading Respondent File and Validating Pregnancy Number Count


In [36]:
# import statements
from __future__ import print_function

import numpy as np
import sys

import nsfg
import thinkstats2

In [42]:
# reading the FemResp file into a data frame
femresp_dct = '2002FemResp.dct'
femresp_dat = '2002FemResp.dat.gz'

# function that reads the dictionary and dat file to turn into data frame
def ReadFemResp(dct_file,dat_file, nrows=None):
    dct = thinkstats2.ReadStataDct(dct_file)
    df = dct.ReadFixedWidth(dat_file, compression = 'gzip', nrows = nrows)
    return df

# initializing the data frame under femresp_df
femresp_df = ReadFemResp(femresp_dct, femresp_dat)

In [46]:
# length check
len(femresp_df)

7643

In [47]:
# wanted to make sure the data frame is loaded
femresp_df

caseid  rscrinf  rdormres  rostscrn  rscreenhisp  rscreenrace  age_a  \
0       2298        1         5         5            1          5.0     27   
1       5012        1         5         1            5          5.0     42   
2      11586        1         5         1            5          5.0     43   
3       6794        5         5         4            1          5.0     15   
4        616        1         5         4            1          5.0     20   
...      ...      ...       ...       ...          ...          ...    ...   
7638   11018        1         5         2            5          3.0     34   
7639    6075        5         5         3            5          3.0     17   
7640    5649        1         5         2            5          5.0     29   
7641     501        5         5         3            5          2.0     16   
7642   10252        1         5         2            5          2.0     28   

      age_r  cmbirth  agescrn  ...  pubassis_i      basewgt  adj_mod_basewgt  \
0        27      902       27  ...           0  3247.916977      5123.759559   
1        42      718       42  ...           0  2335.279149      2846.799490   
2        43      708       43  ...           0  2335.279149      2846.799490   
3        15     1042       15  ...           0  3783.152221      5071.464231   
4        20      991       20  ...           0  5341.329968      6437.335772   
...     ...      ...      ...  ...         ...          ...              ...   
7638     34      811       34  ...           0  3247.445399      3784.333145   
7639     17     1014       17  ...           0  2273.211779      2497.234491   
7640     29      873       29  ...           0  3247.445399      3569.313710   
7641     16     1034       16  ...           0  5304.160818      5954.644352   
7642     28      889       28  ...           0  3247.445399      3476.637428   

          finalwgt  secu_r  sest  cmintvw  cmlstyr  screentime   intvlngth  
0      5556.717241       2    18     1234     1222    18:26:36  110.492667  
1      4744.191350       2    18     1233     1221    16:30:59   64.294000  
2      4744.191350       2    18     1234     1222    18:19:09   75.149167  
3      5923.977368       2    18     1234     1222    15:54:43   28.642833  
4      7229.128072       2    18     1233     1221    14:19:44   69.502667  
...            ...     ...   ...      ...      ...         ...         ...  
7638   6565.818007       2    76     1228     1216    15:57:38   82.907333  
7639   4392.385746       2    76     1228     1216    18:23:53   54.044833  
7640   6003.228729       2    76     1228     1216    18:42:41   68.168000  
7641  10473.623950       2    76     1228     1216    16:02:45   32.717333  
7642   5847.356491       2    76     1230     1218    12:45:19   74.061500  

[7643 rows x 3087 columns]

In [49]:
# value counts for pregnum from femresp_df, sorted
femresp_df.pregnum.value_counts().sort_index()

0     2610
1     1267
2     1432
3     1110
4      611
5      305
6      150
7       80
8       40
9       21
10       9
11       3
12       2
14       2
19       1
Name: pregnum, dtype: int64

In [50]:
# function that feeds in the respondent data frame and cross-validates data about pregnum with the pregnancy dataframe

def ValidatePregnum(resp_df):
    preg_df = nsfg.ReadFemPreg()
    preg_map = nsfg.MakePregMap(preg_df)
    
    # cross checking each case id from the respondents data frame to the preg_df using preg_map
    
    for i, pregnum in resp_df.pregnum.items():
        caseid = resp_df.caseid[i]
        indices = preg_map[caseid]
        
        # making sure that the length of the indices for pregnancies is equal to the number of pregnancies (pregnum)
        # for each caseid between the respondent and the pregnancy file
        # if not, it can print this statement that says where it doesn't match
        
        if len(indices) != pregnum:
            print(caseid, len(indices), pregnum)
            return False

    
    return True

In [51]:
# checking whether the length of the indicies for pregnancies is equal to pregnum for all case id across both data frames

ValidatePregnum(femresp_df)

True

## 2.1 Summarizing Whether First Babies are Later

Q: Based on the results in this chapter, suppose you were asked to summarize what you learned about whether first babies arrive late. Which summary statistics would you use if you wanted to get a story on the evening news? Which ones would you use if you wanted to reassure an anxious patient?

A: If I were to get on the news, I would most likely use summary statistics such as the mean, standard deviation and variance for all live births then compare the means between the first babies and others. I could also discuss outliers of the data sets, weeks less than 10 which are most likely errors and between 10 and 30 can be labeled as premature. I would also report the Cohen's effect size regarding the two populations and try to explain how effect size shows that first week babies arrive late, but being first doesn't prove why they are late. The actual effect size is quite small so that should be taken into account on the news report.

For an anxious patient I would stick to talking about the average pregnancy length, and maybe discuss a bit about the outliers. Probably not too much of an exaggeration, but talking about pregnancy lengths that are below 30 weeks and sometimes a bit over 42 are possible and nothing to worry about. 

Q: Finally, imagine that you are Cecil Adams, author of The Straight Dope (http://straightdope.com), and your job is to answer the question, “Do first babies arrive late?” Write a paragraph that uses the results in this chapter to answer the question clearly, precisely, and honestly.

A: Do first babies arrive late? This is often a question that both anxious patients and the general public happen to ask all the time. Well, based on data from the NSFG, the average pregnancy length of a live birth is around 39 weeks with a standard deviation around 3 weeks. The average pregnancy length for a first baby is around 38.6 weeks and the average pregnancy length for all other births is around 38.5 weeks. At first glance, there isn't much of a difference. An average of 0.1 weeks between births is a very small difference between the two. To explain things further, we can take a look at the effect size between populations, considering the effect of a first birth. Cohen's d is an effect size that compares between the two means, and the value for these two groups is 0.028. Since this effect size is very small, it's actually very hard to say that first pregnancies actually have an effect on pregnancy length compared to others. In conclusion, first pregnancies don't have much of an effect on pregnancy length as much people would expect. 

## 2.4 Cohen Effect Size

In [36]:
firsts.prglngth.mean(), others.prglngth.mean()

(38.60095173351461, 38.52291446673706)

And here's the difference (in weeks):

In [37]:
firsts.prglngth.mean() - others.prglngth.mean()

0.07803726677754952

In [38]:
def CohenEffectSize(group1, group2):
    """Computes Cohen's effect size for two groups.
    
    group1: Series or DataFrame
    group2: Series or DataFrame
    
    returns: float if the arguments are Series;
             Series if the arguments are DataFrames
    """
    diff = group1.mean() - group2.mean()

    var1 = group1.var()
    var2 = group2.var()
    n1, n2 = len(group1), len(group2)

    pooled_var = (n1 * var1 + n2 * var2) / (n1 + n2)
    d = diff / np.sqrt(pooled_var)
    return d

Compute the Cohen effect size for the difference in pregnancy length for first babies and others.

In [40]:
CohenEffectSize(firsts.prglngth, others.prglngth)

0.028879044654449883

Using the variable `totalwgt_lb`, investigate whether first babies are lighter or heavier than others. 

Compute Cohen’s effect size to quantify the difference between the groups.  How does it compare to the difference in pregnancy length?

In [42]:
# finding the mean of the total weights in pounds
firsts.totalwgt_lb.mean(), others.totalwgt_lb.mean()

(7.201094430437772, 7.325855614973262)

In [43]:
firsts.totalwgt_lb.mean() - others.totalwgt_lb.mean()

-0.12476118453549034

First babies are lighter than others by 0.124 pounds on average. 

In [44]:
# computing Cohen's effect size to quantify the difference between groups
CohenEffectSize(firsts.totalwgt_lb,others.totalwgt_lb)

-0.088672927072602

In comparison to the Cohen's effect size of pregnancy length, Cohen's effect size of birthweight and further away from zero. This means that early babies could have an effect of having less weight, but only a small amount. In comparison to pregnancy lengths where first pregnancies could have longer pregnancy lengths than others. Both of the effect sizes are very small. The significance of Cohen's effect size isn't to prove that the effect exists, only to show to a certainty that it is real. Since our effect size is close to 0, 0.1, the effect size is small. 